#!/bin/bash
echo "This is a repository for C variables" >> README.md
echo "chmod u+x * 
chmod u-x README.md
git add .
git commit -m \"This file is for c loop variables\"
git push" >> automate
touch 0-positive_or_negative.c
touch 1-last_digit.c
touch 2-print_alphabet.c 3-print_alphabets.c 4-print_alphabt.c 5-print_numbers.c 6-print_numberz.c
touch 7-print_tebahpla.c 8-print_base16.c 9-print_comb.c
